#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# With these Requirements:
# - Configure HAproxy so that it send traffic to web-01 and web-02
# - Distribute requests using a roundrobin algorithm
# - Make sure that HAproxy can be managed via an init script
# - Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 389033-web-01 54.209.197.247:80 check
    server 389033-web-02 54.157.152.16:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
