#!/usr/bin/env bash
# Configure ufw
# Except 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 20/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
